# Background pipeline overrides for the shared config.
# This file is combined with config/config.yaml at runtime.
---
output: "{{PATH_TO_REPO}}/pickett_bcr_abl_pipeline/config/output_files_background.yaml"

dotnet_pisces:
  extra: "--gvcf TRUE --filterduplicates TRUE"
