---
# Shared pipeline config.
# Cluster-specific paths and reference registries live under:
# - config/site_configs/
# - config/reference_files/
PIPELINE_VERSION: v0.2.2

CONFIG_DIR: "{{PATH_TO_REPO}}/pickett_bcr_abl_pipeline/config"
ANNOTATIONS: "{{PATH_TO_REPO}}/pickett_bcr_abl_pipeline/config/annotations_hg19"

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "{{CONFIG_DIR}}/output_files.yaml"

default_container: '{{APPTAINER_CACHE}}/hydragenetics_common_1.11.1.sif'

modules:
  alignment: v0.6.0
  annotation: b25e8ea
  snv_indels: ebf6671
  prealignment: v1.2.0
  fusions: v0.2.2
  qc: 2c37a18

reference:
  genome_dir: "{{REFERENCE_DATA}}/" # req by align not used
  fasta: "{{REFERENCE_DATA}}/hg19.with.mt.fasta"
  fai: "{{REFERENCE_DATA}}/hg19.with.mt.fasta.fai"
  genomesize_xml: "{{REFERENCE_DATA}}/GenomeSize.xml"
  design_bed: "{{ANNOTATIONS}}/bcr_abl1.bed"
  background: "{{REFERENCE_DATA}}/background_panel.tsv"
  skip_chrs:
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chr20"
    - "chr21"
    - "chrX"
    - "chrY"
    - "chrM"

arriba:
  container: '{{APPTAINER_CACHE}}/hydragenetics_arriba_2.3.0.sif'
  assembly: "{{REFERENCE_DATA}}/hg19.with.mt.fasta"
  blacklist: "{{REFERENCE_DATA}}/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"
  gtf: "{{REFERENCE_DATA}}/hg19.refGene.gtf"
  extra: "-p {{REFERENCE_DATA}}/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3 -k {{REFERENCE_DATA}}/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"

arriba_draw_fusion:
  container: '{{APPTAINER_CACHE}}/hydragenetics_arriba_2.3.0.sif'
  cytobands: "{{REFERENCE_DATA}}/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv"
  gtf: "{{REFERENCE_DATA}}/hg19.refGene.gtf"
  protein_domains: "{{REFERENCE_DATA}}/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3"

convert_pdf:
  container: '{{APPTAINER_CACHE}}/dpokidov_imagemagick_7.1.0-47-ubuntu.sif'

dotnet_pisces:
  container: '{{APPTAINER_CACHE}}/_container_pisces_v5.2.11.sif' # illumina pisces v5.2.11

fastp_pe:
  container: '{{APPTAINER_CACHE}}/hydragenetics_fastp_0.20.1.sif'
  extra: "-x "

fastqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics_fastqc_0.11.9.sif'

fusioncatcher: # not used but req
  container: '{{APPTAINER_CACHE}}/hydragenetics_fusioncatcher_1.33.sif'
  genome_path: ""

mosdepth_bed:
  container: '{{APPTAINER_CACHE}}/hydragenetics_mosdepth_0.3.2.sif'
  design_bed: "{{ANNOTATIONS}}/branford_SNVs_230118.bed"

multiqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics_multiqc_1.11.sif'
  reports:
    RNA:
      config: "{{CONFIG_DIR}}/multiqc_config_rna.yaml"
      included_unit_types: ["R"]
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
        - "alignment/star/{sample}_{type}.Log.final.out"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed/{sample}_{type}.regions.bed.gz"
        - "qc/mosdepth_bed/{sample}_{type}.regions.bed.gz.csi"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/rseqc_gene_body_coverage/{sample}_{type}.geneBodyCoverage.txt"
        - "qc/rseqc_inner_distance/{sample}_{type}.inner_distance_freq.txt"

rseqc_gene_body_coverage:
  bed: "{{ANNOTATIONS}}/bcr_abl1_rseqc.bed"
  container: '{{APPTAINER_CACHE}}/hydragenetics_rseqc_4.0.0.sif'

rseqc_inner_distance:
  bed: "{{ANNOTATIONS}}/bcr_abl1_rseqc.bed"
  container: '{{APPTAINER_CACHE}}/hydragenetics_rseqc_4.0.0.sif'

star:
  container: '{{APPTAINER_CACHE}}/hydragenetics_star_2.7.10a.sif'
  genome_index: "{{REFERENCE_DATA}}/star_index_v2.7.10a_hg19/"
  extra: "--outSAMmapqUnique 60 --quantMode GeneCounts --sjdbGTFfile {{REFERENCE_DATA}}/hg19.refGene.gtf --outSAMtype BAM SortedByCoordinate --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3"

star_fusion:
  container: '{{APPTAINER_CACHE}}/hydragenetics_star-fusion_1.10.1.sif'
  genome_path: "{{REFERENCE_DATA}}/star-fusion/GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/"

summary_report:
  branford: "{{ANNOTATIONS}}/branford_SNVs_230118.bed"

trimmer_software: "fastp_pe"

vt_decompose:
  container: '{{APPTAINER_CACHE}}/hydragenetics_vt_2015.11.10.sif'

vt_normalize:
  container: '{{APPTAINER_CACHE}}/hydragenetics_vt_2015.11.10.sif'
