---

default_resources:
  threads: 1
  time: "8:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: core

dotnet_pisces:
  threads: 2

fastp_pe:
  mem_mb: 49152
  threads: 2

fastqc:
  mem_mb: 49152
  threads: 2

mosdepth_bed:
  mem_mb: 24576
  threads: 3

star:
  mem_mb: 49152
  threads: 4

