jobs: 100
keep-going: true
restart-times: 1
rerun-incomplete: true
max-jobs-per-second: 100
max-status-checks-per-second: 100
use-singularity: true
drmaa: "-p {resources.partition} -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} -J {rule} -A wp2 -e slurm/{rule}_%j.err -o slurm/{rule}_%j.out --nodes=1-1"
drmaa-log-dir: slurm
singularity-args: "--cleanenv --bind /beegfs-archive,/beegfs-scratch,/beegfs-storage,/home,/data,/projects -B /beegfs-scratch/wp4/wp2_wgs_tmp:/tmp --nv"
singularity-prefix: "/projects/bin/wp2_abl/apptainer_cache/"
wrapper-prefix: "git+file:///projects/bin/wp2_abl/snakemake-wrappers/"
